### ISSUE TITLE
Themer disappeared when addon installed

### ISSUE THREAD

**Issue by RamonaMarie** [pods-framework/pods-beaver-builder-themer-add-on#44] opened 2017-08-22 13:12 UTC
I'm using Beaver Builder plugin (pro), theme and themer. I installed Pods Beaver Themer Add-On. I think it made my Themer Builder icon in the sidebar disappear. I installed addon from WP respository. https://www.screencast.com/t/H7F9iifjoR8O #beaver-themer

I also posted in slack channel and to BB. Thanks.

**Comment by quasel** [comment] 2017-08-28 13:36
Sorry can't reproduce that :/ im using BB Pro, Theme and Themer and you are the first to experience it  - strange thing although  - did you try with WP_DEBUG true? and see if any error pops up? deactivate all other stuff? maybe something is interfering!

**Comment by quasel** [comment] 2017-09-05 13:53
Going to close the issue - if you still encounter the problem feel free to comment again!

**Closed by quasel** 2017-09-05 13:53 UTC
